<?xml version="1.0"?>
<!DOCTYPE core-data [
	<!ELEMENT core-data (
		manifest*,
		project*)>
	<!ATTLIST core-data
		version CDATA #REQUIRED
		time-stamp CDATA #REQUIRED
		exported-by CDATA #REQUIRED
		xmlns CDATA #FIXED "http://www.vitechcorp.com/xml-schemas/core50">
	<!ELEMENT manifest (project-manifest*)>
	<!ATTLIST manifest
		users-and-groups CDATA #REQUIRED
		settings CDATA #REQUIRED>
	<!ELEMENT project (
		acl*,
		model*,
		presentation*)>
	<!ATTLIST project
		name CDATA #REQUIRED
		permission-level CDATA #REQUIRED
		description CDATA #IMPLIED
		creator CDATA #REQUIRED
		created CDATA #REQUIRED
		modified CDATA #REQUIRED
		baseline-schema CDATA #REQUIRED
		schema-version CDATA #REQUIRED>
	<!ELEMENT project-manifest EMPTY>
	<!ATTLIST project-manifest
		project CDATA #REQUIRED
		schema-version CDATA #REQUIRED
		baseline-schema CDATA #REQUIRED
		permission-level CDATA #REQUIRED
		incremental CDATA #REQUIRED
		erase-history CDATA #REQUIRED
		plain-text CDATA #REQUIRED
		include-names CDATA #REQUIRED
		database CDATA #REQUIRED
		database-view-descriptions CDATA #REQUIRED
		schema CDATA #REQUIRED
		schema-view-descriptions CDATA #REQUIRED
		filter-definitions CDATA #REQUIRED
		sort-definitions CDATA #REQUIRED
		facilities CDATA #REQUIRED
		hierarchy-definitions CDATA #REQUIRED
		folders CDATA #REQUIRED>
	<!ELEMENT acl (ace*)>
	<!ELEMENT model (
		schema-model*,
		database-model*)>
	<!ELEMENT presentation (
		schema-presentation*,
		database-presentation*)>
	<!ELEMENT ace EMPTY>
	<!ATTLIST ace
		uid CDATA #REQUIRED
		permissions CDATA #REQUIRED>
	<!ELEMENT schema-model (
		relationship-definition*,
		element-definition*,
		entity-relationship-association*,
		facility*)>
	<!ELEMENT database-model (
		folder*,
		entity*,
		relationship*,
		structure*)>
	<!ELEMENT schema-presentation (structure-representation*)>
	<!ELEMENT database-presentation (structure-representation*)>
	<!ELEMENT relationship-definition (
		property*,
		attribute-definition*)>
	<!ATTLIST relationship-definition
		name CDATA #REQUIRED
		attribute-order CDATA #IMPLIED
		required-attribute-definitions CDATA #IMPLIED
		action CDATA #IMPLIED>
	<!ELEMENT element-definition (
		property*,
		attribute-definition*,
		entity-attribute-association*)>
	<!ATTLIST element-definition
		name CDATA #REQUIRED
		superclass CDATA #IMPLIED
		attribute-order CDATA #IMPLIED
		parent-child-relation CDATA #IMPLIED
		required-attribute-definitions CDATA #IMPLIED
		required-relationship-definitions CDATA #IMPLIED
		action CDATA #IMPLIED>
	<!ELEMENT entity-relationship-association (target*)>
	<!ATTLIST entity-relationship-association
		definition CDATA #REQUIRED
		name CDATA #REQUIRED
		action CDATA #IMPLIED>
	<!ELEMENT facility (
		property*,
		class*)>
	<!ATTLIST facility
		name CDATA #REQUIRED
		action CDATA #IMPLIED>
	<!ELEMENT folder EMPTY>
	<!ATTLIST folder
		name CDATA #REQUIRED>
	<!ELEMENT entity (
		acl*,
		attribute*,
		collection-attribute*,
		script-spec-attribute*,
		random-spec-attribute*,
		constant-spec-attribute*,
		reference-spec-attribute*,
		category*)>
	<!ATTLIST entity
		id CDATA #IMPLIED
		name CDATA #IMPLIED
		definition CDATA #IMPLIED>
	<!ELEMENT relationship (
		attribute*,
		collection-attribute*,
		script-spec-attribute*,
		random-spec-attribute*,
		constant-spec-attribute*,
		reference-spec-attribute*)>
	<!ATTLIST relationship
		source-definition CDATA #IMPLIED
		source-name CDATA #IMPLIED
		source-id CDATA #IMPLIED
		definition CDATA #REQUIRED
		target-definition CDATA #IMPLIED
		target-name CDATA #IMPLIED
		target-id CDATA #IMPLIED>
	<!ELEMENT structure (branch*)>
	<!ATTLIST structure
		id CDATA #REQUIRED
		definition CDATA #IMPLIED
		name CDATA #IMPLIED>
	<!ELEMENT structure-representation (
		navigation-key*,
		diagram-parameter*,
		construct-representation*)>
	<!ATTLIST structure-representation
		frozen CDATA #REQUIRED
		user-id CDATA #REQUIRED
		created CDATA #REQUIRED
		accessed CDATA #REQUIRED>
	<!ELEMENT property (#PCDATA | plain-text)*>
	<!ATTLIST property
		name CDATA #REQUIRED>
	<!ELEMENT attribute-definition (
		property*,
		possible-values*,
		initial-value*)>
	<!ATTLIST attribute-definition
		name CDATA #REQUIRED
		action CDATA #IMPLIED>
	<!ELEMENT entity-attribute-association (
		property*,
		possible-values*,
		initial-value*)>
	<!ATTLIST entity-attribute-association
		name CDATA #REQUIRED>
	<!ELEMENT target EMPTY>
	<!ATTLIST target
		action CDATA #IMPLIED
		new-name CDATA #IMPLIED
		name CDATA #REQUIRED>
	<!ELEMENT class (#PCDATA)>
	<!ATTLIST class
		action CDATA #IMPLIED
		new-name CDATA #IMPLIED>
	<!ELEMENT attribute (#PCDATA |
		acl |
		plain-text)*>
	<!ATTLIST attribute
		name CDATA #REQUIRED
		changed CDATA #IMPLIED
		changed-by CDATA #IMPLIED>
	<!ELEMENT collection-attribute (value*)>
	<!ATTLIST collection-attribute
		name CDATA #REQUIRED
		changed CDATA #IMPLIED
		changed-by CDATA #IMPLIED>
	<!ELEMENT script-spec-attribute (script-construct*)>
	<!ATTLIST script-spec-attribute
		name CDATA #REQUIRED
		changed CDATA #IMPLIED
		changed-by CDATA #IMPLIED
		script-name CDATA #IMPLIED
		script-version CDATA #REQUIRED
		script-type CDATA #REQUIRED
		script-description CDATA #IMPLIED
		help-file-name CDATA #IMPLIED
		parameters CDATA #IMPLIED
		locals CDATA #IMPLIED
		globals CDATA #IMPLIED>
	<!ELEMENT random-spec-attribute (random-spec-argument*)>
	<!ATTLIST random-spec-attribute
		name CDATA #REQUIRED
		changed CDATA #IMPLIED
		changed-by CDATA #IMPLIED
		distribution CDATA #REQUIRED
		stream-id CDATA #REQUIRED>
	<!ELEMENT constant-spec-attribute (#PCDATA)>
	<!ATTLIST constant-spec-attribute
		name CDATA #REQUIRED
		changed CDATA #IMPLIED
		changed-by CDATA #IMPLIED>
	<!ELEMENT reference-spec-attribute (#PCDATA)>
	<!ATTLIST reference-spec-attribute
		name CDATA #REQUIRED
		changed CDATA #IMPLIED
		changed-by CDATA #IMPLIED>
	<!ELEMENT category (#PCDATA)>
	<!ATTLIST category
		action CDATA #REQUIRED>
	<!ELEMENT branch (
		parallel |
		select |
		iterate |
		loop |
		replicate |
		function |
		loop-exit |
		exit)*>
	<!ATTLIST branch
		net-id CDATA #REQUIRED
		annotation CDATA #IMPLIED>
	<!ELEMENT navigation-key (diagram-specifier*)>
	<!ATTLIST navigation-key
		diagram CDATA #REQUIRED
		view CDATA #REQUIRED
		database-object-class CDATA #REQUIRED
		database-object CDATA #REQUIRED
		element-name CDATA #IMPLIED
		element-definition CDATA #IMPLIED>
	<!ELEMENT diagram-parameter (parameter*)>
	<!ELEMENT construct-representation (
		diagram-object-color-profile*,
		uid*,
		network-uid*,
		label-uid*,
		diagram-note*,
		polyline-with-end-icons*)>
	<!ATTLIST construct-representation
		anchored CDATA #IMPLIED
		anchor-offset CDATA #IMPLIED
		base-origin CDATA #IMPLIED
		grow-box CDATA #IMPLIED
		icon-size CDATA #IMPLIED
		dynamic-size CDATA #IMPLIED
		color CDATA #IMPLIED
		state CDATA #IMPLIED
		direction CDATA #IMPLIED>
	<!ELEMENT plain-text (#PCDATA)>
	<!ELEMENT possible-values (item*)>
	<!ATTLIST possible-values
		order CDATA #REQUIRED>
	<!ELEMENT initial-value (#PCDATA |
		value |
		script-spec |
		random-spec |
		constant-spec |
		reference-spec)*>
	<!ELEMENT value (#PCDATA)>
	<!ATTLIST value
		action CDATA #IMPLIED
		new-name CDATA #IMPLIED>
	<!ELEMENT script-construct (
		script-spec-argument*,
		script-property*,
		script-construct*,
		representation-field*)>
	<!ATTLIST script-construct
		name CDATA #REQUIRED>
	<!ELEMENT random-spec-argument (#PCDATA)>
	<!ATTLIST random-spec-argument
		name CDATA #REQUIRED>
	<!ELEMENT parallel (parallel-branch*)>
	<!ATTLIST parallel
		net-id CDATA #REQUIRED>
	<!ELEMENT select (selection-branch*)>
	<!ATTLIST select
		net-id CDATA #REQUIRED>
	<!ELEMENT iterate (branch*)>
	<!ATTLIST iterate
		net-id CDATA #REQUIRED
		id CDATA #IMPLIED
		name CDATA #IMPLIED
		definition CDATA #IMPLIED>
	<!ELEMENT loop (branch*)>
	<!ATTLIST loop
		net-id CDATA #REQUIRED
		loop-condition CDATA #IMPLIED>
	<!ELEMENT replicate (
		parallel-branch*,
		coordination-branch*)>
	<!ATTLIST replicate
		net-id CDATA #REQUIRED
		id CDATA #REQUIRED
		definition CDATA #IMPLIED
		name CDATA #IMPLIED>
	<!ELEMENT function (exit-branch*)>
	<!ATTLIST function
		net-id CDATA #REQUIRED
		id CDATA #REQUIRED
		name CDATA #IMPLIED
		definition CDATA #IMPLIED>
	<!ELEMENT loop-exit EMPTY>
	<!ATTLIST loop-exit
		net-id CDATA #REQUIRED>
	<!ELEMENT exit EMPTY>
	<!ATTLIST exit
		net-id CDATA #REQUIRED
		id CDATA #IMPLIED
		definition CDATA #IMPLIED
		name CDATA #IMPLIED>
	<!ELEMENT diagram-specifier (relation*)>
	<!ATTLIST diagram-specifier
		name CDATA #REQUIRED
		description CDATA #IMPLIED
		label CDATA #IMPLIED
		show-relationships CDATA #REQUIRED
		essential CDATA #REQUIRED>
	<!ELEMENT parameter (
		color-profile*,
		icon-profile*,
		scale-profile*)>
	<!ATTLIST parameter
		frame-only CDATA #REQUIRED
		show-data-stores CDATA #IMPLIED
		show-frame CDATA #REQUIRED
		show-reference-nodes CDATA #IMPLIED
		show-triggers CDATA #IMPLIED
		store-view-settings CDATA #IMPLIED
		levels CDATA #IMPLIED
		show-relationship-labels CDATA #IMPLIED
		use-compact-placement CDATA #IMPLIED
		show-grid CDATA #IMPLIED
		use-aliases CDATA #IMPLIED
		show-external-items CDATA #IMPLIED
		show-box-numbers CDATA #IMPLIED
		show-protocol-warnings CDATA #IMPLIED
		show-all-relations CDATA #IMPLIED
		element-sort-block-name CDATA #IMPLIED
		use-dre CDATA #IMPLIED>
	<!ELEMENT diagram-object-color-profile EMPTY>
	<!ATTLIST diagram-object-color-profile
		back CDATA #IMPLIED
		line CDATA #IMPLIED
		text CDATA #IMPLIED>
	<!ELEMENT uid (
		element-reference |
		relationship-reference |
		relation |
		note-id |
		element-definition-reference |
		attribute-definition-reference |
		boolean |
		symbol)*>
	<!ATTLIST uid
		definition CDATA #REQUIRED>
	<!ELEMENT network-uid (
		element-reference |
		relationship-reference |
		relation |
		note-id |
		element-definition-reference |
		attribute-definition-reference |
		boolean |
		symbol)*>
	<!ATTLIST network-uid
		definition CDATA #REQUIRED
		net-id CDATA #REQUIRED>
	<!ELEMENT label-uid (
		(
			element-reference |
			relationship-reference |
			relation |
			note-id |
			element-definition-reference |
			attribute-definition-reference |
			boolean |
			symbol)*,
		uid*)>
	<!ATTLIST label-uid
		definition CDATA #REQUIRED>
	<!ELEMENT diagram-note (uid*)>
	<!ATTLIST diagram-note
		object CDATA #IMPLIED
		base-origin CDATA #IMPLIED
		extent CDATA #IMPLIED
		line-style CDATA #IMPLIED
		fill-style CDATA #IMPLIED
		horizontal-alignment CDATA #IMPLIED
		vertical-alignment CDATA #IMPLIED>
	<!ELEMENT polyline-with-end-icons (
		point*,
		(
			arrowhead |
			double-arrowhead |
			filled-double-arrowhead |
			filled-arrowhead |
			filled-circle |
			filled-rectangle |
			filled-whole-circle |
			nil-geometric-object |
			rectangle |
			whole-circle)*)>
	<!ATTLIST polyline-with-end-icons
		start-truncated CDATA #REQUIRED
		end-truncated CDATA #REQUIRED>
	<!ELEMENT item EMPTY>
	<!ATTLIST item
		action CDATA #IMPLIED
		new-name CDATA #IMPLIED
		name CDATA #IMPLIED>
	<!ELEMENT script-spec (script-construct*)>
	<!ATTLIST script-spec
		script-name CDATA #IMPLIED
		version CDATA #REQUIRED
		type CDATA #REQUIRED
		description CDATA #IMPLIED
		help-file-name CDATA #IMPLIED
		parameters CDATA #IMPLIED
		locals CDATA #IMPLIED
		globals CDATA #IMPLIED>
	<!ELEMENT random-spec (random-spec-argument*)>
	<!ATTLIST random-spec
		distribution CDATA #REQUIRED
		stream-id CDATA #REQUIRED>
	<!ELEMENT constant-spec (#PCDATA)>
	<!ELEMENT reference-spec (#PCDATA)>
	<!ELEMENT script-spec-argument (#PCDATA)>
	<!ATTLIST script-spec-argument
		name CDATA #REQUIRED>
	<!ELEMENT script-property (#PCDATA |
		plain-text |
		value)*>
	<!ATTLIST script-property
		name CDATA #REQUIRED>
	<!ELEMENT representation-field EMPTY>
	<!ATTLIST representation-field
		type CDATA #REQUIRED
		name CDATA #IMPLIED
		literal CDATA #IMPLIED
		leading-text CDATA #IMPLIED
		separating-text CDATA #IMPLIED
		trailing-text CDATA #IMPLIED
		sort-name CDATA #IMPLIED>
	<!ELEMENT parallel-branch (
		parallel |
		select |
		iterate |
		loop |
		replicate |
		function |
		loop-exit |
		exit)*>
	<!ATTLIST parallel-branch
		net-id CDATA #REQUIRED
		annotation CDATA #IMPLIED
		kill-status CDATA #IMPLIED>
	<!ELEMENT selection-branch (
		parallel |
		select |
		iterate |
		loop |
		replicate |
		function |
		loop-exit |
		exit)*>
	<!ATTLIST selection-branch
		net-id CDATA #REQUIRED
		annotation CDATA #IMPLIED
		selection-probability CDATA #IMPLIED>
	<!ELEMENT coordination-branch (
		parallel |
		select |
		iterate |
		loop |
		replicate |
		function |
		loop-exit |
		exit)*>
	<!ATTLIST coordination-branch
		net-id CDATA #REQUIRED
		annotation CDATA #IMPLIED
		kill-status CDATA #IMPLIED>
	<!ELEMENT exit-branch (
		parallel |
		select |
		iterate |
		loop |
		replicate |
		function |
		loop-exit |
		exit)*>
	<!ATTLIST exit-branch
		net-id CDATA #REQUIRED
		id CDATA #IMPLIED
		definition CDATA #IMPLIED
		name CDATA #IMPLIED>
	<!ELEMENT relation (#PCDATA)>
	<!ELEMENT color-profile EMPTY>
	<!ATTLIST color-profile
		alias CDATA #IMPLIED
		back CDATA #IMPLIED
		line CDATA #IMPLIED
		text CDATA #IMPLIED>
	<!ELEMENT icon-profile (
		icon-template*,
		icon-multi-object*)>
	<!ATTLIST icon-profile
		type CDATA #REQUIRED
		back-color CDATA #IMPLIED
		line-color CDATA #IMPLIED
		text-color CDATA #IMPLIED
		size CDATA #REQUIRED
		spacing CDATA #REQUIRED>
	<!ELEMENT scale-profile EMPTY>
	<!ATTLIST scale-profile
		font-factor CDATA #REQUIRED
		mode CDATA #REQUIRED
		scale CDATA #REQUIRED
		size-factor  CDATA #REQUIRED>
	<!ELEMENT element-reference EMPTY>
	<!ATTLIST element-reference
		id CDATA #REQUIRED
		name CDATA #IMPLIED
		definition CDATA #IMPLIED>
	<!ELEMENT relationship-reference EMPTY>
	<!ATTLIST relationship-reference
		source-definition CDATA #IMPLIED
		source-name CDATA #IMPLIED
		source-id CDATA #REQUIRED
		definition CDATA #REQUIRED
		target-definition CDATA #IMPLIED
		target-name CDATA #IMPLIED
		target-id CDATA #REQUIRED>
	<!ELEMENT note-id (#PCDATA)>
	<!ELEMENT element-definition-reference EMPTY>
	<!ATTLIST element-definition-reference
		name CDATA #REQUIRED>
	<!ELEMENT attribute-definition-reference EMPTY>
	<!ATTLIST attribute-definition-reference
		name CDATA #REQUIRED
		owner CDATA #REQUIRED
		class CDATA #REQUIRED>
	<!ELEMENT boolean EMPTY>
	<!ATTLIST boolean
		value CDATA #REQUIRED>
	<!ELEMENT symbol (#PCDATA)>
	<!ELEMENT point EMPTY>
	<!ATTLIST point
		x CDATA #REQUIRED
		y CDATA #REQUIRED>
	<!ELEMENT arrowhead (point*)>
	<!ATTLIST arrowhead
		edge-length CDATA #REQUIRED>
	<!ELEMENT double-arrowhead (point*)>
	<!ATTLIST double-arrowhead
		edge-length CDATA #REQUIRED>
	<!ELEMENT filled-double-arrowhead (point*)>
	<!ATTLIST filled-double-arrowhead
		edge-length CDATA #REQUIRED>
	<!ELEMENT filled-arrowhead (point*)>
	<!ATTLIST filled-arrowhead
		edge-length CDATA #REQUIRED>
	<!ELEMENT filled-circle EMPTY>
	<!ATTLIST filled-circle
		left-top CDATA #REQUIRED
		right-bottom CDATA #REQUIRED>
	<!ELEMENT filled-rectangle EMPTY>
	<!ATTLIST filled-rectangle
		left-top CDATA #REQUIRED
		right-bottom CDATA #REQUIRED>
	<!ELEMENT filled-whole-circle EMPTY>
	<!ATTLIST filled-whole-circle
		left-top CDATA #REQUIRED
		right-bottom CDATA #REQUIRED>
	<!ELEMENT nil-geometric-object EMPTY>
	<!ELEMENT rectangle EMPTY>
	<!ATTLIST rectangle
		left-top CDATA #REQUIRED
		right-bottom CDATA #REQUIRED>
	<!ELEMENT whole-circle EMPTY>
	<!ATTLIST whole-circle
		left-top CDATA #REQUIRED
		right-bottom CDATA #REQUIRED>
	<!ELEMENT icon-template (
		icon-frame*,
		(
			icon-attribute |
			icon-separator |
			icon-element |
			icon-class)*)>
	<!ATTLIST icon-template
		name CDATA #IMPLIED>
	<!ELEMENT icon-multi-object (
		icon-frame*,
		representation-field*)>
	<!ATTLIST icon-multi-object
		name CDATA #REQUIRED
		alignment CDATA #REQUIRED
		separator-type CDATA #REQUIRED>
	<!ELEMENT icon-frame (
		rectangle*,
		ellipse*,
		rounded-rectangle*,
		circle*)>
	<!ELEMENT icon-attribute EMPTY>
	<!ATTLIST icon-attribute
		alignment CDATA #REQUIRED
		leading CDATA #REQUIRED
		trailing CDATA #REQUIRED
		leading-text CDATA #IMPLIED
		min-lines CDATA #REQUIRED
		trailing-text CDATA #IMPLIED
		extra-space CDATA #REQUIRED
		attribute CDATA #REQUIRED>
	<!ELEMENT icon-separator EMPTY>
	<!ATTLIST icon-separator
		type CDATA #REQUIRED>
	<!ELEMENT icon-element EMPTY>
	<!ATTLIST icon-element
		alignment CDATA #REQUIRED
		leading CDATA #REQUIRED
		trailing CDATA #REQUIRED
		leading-text CDATA #IMPLIED
		min-lines CDATA #REQUIRED
		trailing-text CDATA #IMPLIED
		extra-space CDATA #REQUIRED>
	<!ELEMENT icon-class EMPTY>
	<!ATTLIST icon-class
		alignment CDATA #REQUIRED
		leading CDATA #REQUIRED
		trailing CDATA #REQUIRED
		leading-text CDATA #IMPLIED
		min-lines CDATA #REQUIRED
		trailing-text CDATA #IMPLIED
		extra-space CDATA #REQUIRED
		property CDATA #REQUIRED>
	<!ELEMENT ellipse EMPTY>
	<!ATTLIST ellipse
		left-top CDATA #REQUIRED
		right-bottom CDATA #REQUIRED>
	<!ELEMENT rounded-rectangle EMPTY>
	<!ATTLIST rounded-rectangle
		left-top CDATA #REQUIRED
		right-bottom CDATA #REQUIRED
		rounding-extent CDATA #REQUIRED>
	<!ELEMENT circle EMPTY>
	<!ATTLIST circle
		left-top CDATA #REQUIRED
		right-bottom CDATA #REQUIRED>]>
<core-data
	version = '5.1'
	time-stamp = '01/28/2013 at 17:51:01'
	exported-by = 'Administrator'
	xmlns = 'http://www.vitechcorp.com/xml-schemas/core50'>
	<manifest
		users-and-groups = 'false'
		settings = 'false'>
		<project-manifest
			project = 'On Sight'
			schema-version = '5.0'
			baseline-schema = 'Base Schema v50'
			permission-level = 'element'
			incremental = 'false'
			erase-history = 'false'
			plain-text = 'false'
			include-names = 'true'
			database = 'true'
			database-view-descriptions = 'true'
			schema = 'true'
			schema-view-descriptions = 'true'
			filter-definitions = 'false'
			sort-definitions = 'false'
			facilities = 'true'
			hierarchy-definitions = 'false'
			folders = 'true'/>
	</manifest>
	<project
		name = 'On Sight'
		permission-level = 'element'
		creator = 'Administrator'
		created = '09/28/2004 at 09:10:58'
		modified = '09/28/2004 at 09:10:58'
		baseline-schema = 'Base Schema v50'
		schema-version = '5.0'>
		<acl>
			<ace
				uid = '{00000000-0000-0000-0000-0000DA390000}'
				permissions = '123'/>
		</acl>
		<model>
			<schema-model>
				<relationship-definition
					action = 'delete'
					name = 'accomplished by'/>
				<relationship-definition
					action = 'delete'
					name = 'accomplishes'/>
				<relationship-definition
					action = 'delete'
					name = 'categorized by'/>
				<relationship-definition
					action = 'delete'
					name = 'categorizes'/>
				<relationship-definition
					action = 'delete'
					name = 'defined by'/>
				<relationship-definition
					action = 'delete'
					name = 'defines'/>
				<relationship-definition
					action = 'delete'
					name = 'employed by'/>
				<relationship-definition
					action = 'delete'
					name = 'employs'/>
				<relationship-definition
					action = 'delete'
					name = 'exhibited by'/>
				<relationship-definition
					action = 'delete'
					name = 'exhibits'/>
				<relationship-definition
					action = 'delete'
					name = 'formats'/>
				<relationship-definition
					action = 'delete'
					name = 'formatted by'/>
				<relationship-definition
					action = 'delete'
					name = 'formed by'/>
				<relationship-definition
					action = 'delete'
					name = 'forms'/>
				<relationship-definition
					action = 'delete'
					name = 'fulfilled by'/>
				<relationship-definition
					action = 'delete'
					name = 'fulfills'/>
				<relationship-definition
					action = 'delete'
					name = 'included in'/>
				<relationship-definition
					action = 'delete'
					name = 'includes'/>
				<relationship-definition
					action = 'delete'
					name = 'reported by'/>
				<relationship-definition
					action = 'delete'
					name = 'reports on'/>
				<relationship-definition
					action = 'delete'
					name = 'supplied by'/>
				<relationship-definition
					action = 'delete'
					name = 'supplies'/>
				<relationship-definition
					action = 'delete'
					name = 'utilized by'/>
				<relationship-definition
					action = 'delete'
					name = 'utilizes'/>
				<relationship-definition
					name = 'signs'>
					<property
						name = 'alias'>
						<![CDATA[approuve]]>
					</property>
					<property
						name = 'description'>
						<![CDATA[{\rtf1\ansi\ansicpg1252\uc0\deff0{\fonttbl
{\f0\froman\fcharset0\fprq2 Times New Roman;}}
{\colortbl;\red0\green0\blue0;\red255\green255\blue255;}
\deftab1134\pard\plain\f0\fs20 Une partie prenante "approuve" un document.}]]>
					</property>
					<property
						name = 'modificationStamp'>
						06/15/2009 at 15:59:13
					</property>
				</relationship-definition>
				<relationship-definition
					name = 'signed by'>
					<property
						name = 'alias'>
						<![CDATA[approuvé par]]>
					</property>
					<property
						name = 'description'>
						<![CDATA[{\rtf1\ansi\ansicpg1252\uc0\deff0{\fonttbl
{\f0\froman\fcharset0\fprq2 Times New Roman;}}
{\colortbl;\red0\green0\blue0;\red255\green255\blue255;}
\deftab1134\pard\plain\f0\fs20 Un document est "approuv\'e9 par" une partie prenante.}]]>
					</property>
					<property
						name = 'modificationStamp'>
						06/15/2009 at 15:58:55
					</property>
				</relationship-definition>
				<relationship-definition
					name = 'assigned to'>
					<property
						name = 'alias'>
						<![CDATA[assigné à]]>
					</property>
					<property
						name = 'description'>
						<![CDATA[{\rtf1\ansi\ansicpg1252\uc0\deff0{\fonttbl
{\f0\froman\fcharset0\fprq2 Times New Roman;}}
{\colortbl;\red0\green0\blue0;\red255\green255\blue255;}
\deftab1134\pard\plain\f0\fs20 Assigned to identifies the individual or organizational unit that is responsible for this element.\par Une barri\'e8re est "assign\'e9e" \'e0 un \'e9l\'e9ment de l'architecture.}]]>
					</property>
				</relationship-definition>
				<relationship-definition
					name = 'responsible for'>
					<property
						name = 'alias'>
						<![CDATA[assure]]>
					</property>
					<property
						name = 'description'>
						<![CDATA[{\rtf1\ansi\ansicpg1252\uc0\deff0{\fonttbl
{\f0\froman\fcharset0\fprq2 Times New Roman;}}
{\colortbl;\red0\green0\blue0;\red255\green255\blue255;}
\deftab1134\pard\plain\f0\fs20 Un \'e9l\'e9ment de l'architecture "assure" une barri\'e8re.}]]>
					</property>
					<property
						name = 'modificationStamp'>
						06/22/2009 at 10:52:28
					</property>
				</relationship-definition>
				<relationship-definition
					name = 'contains'>
					<property
						name = 'alias'>
						<![CDATA[complète]]>
					</property>
					<property
						name = 'description'>
						<![CDATA[{\rtf1\ansi\ansicpg1252\uc0\deff0{\fonttbl
{\f0\froman\fcharset0\fprq2 Times New Roman;}}
{\colortbl;\red0\green0\blue0;\red255\green255\blue255;}
\deftab1134\pard\plain\f0\fs20 Un flux externe compl\'e8te une exigence d'interface.}]]>
					</property>
				</relationship-definition>
				<relationship-definition
					name = 'contained by'>
					<property
						name = 'alias'>
						<![CDATA[complété par]]>
					</property>
					<property
						name = 'description'>
						<![CDATA[{\rtf1\ansi\ansicpg1252\uc0\deff0{\fonttbl
{\f0\froman\fcharset0\fprq2 Times New Roman;}}
{\colortbl;\red0\green0\blue0;\red255\green255\blue255;}
\deftab1134\pard\plain\f0\fs20 Une exigence d'interface est "compl\'e9t\'e9e par" un flux externe.}]]>
					</property>
					<property
						name = 'modificationStamp'>
						06/22/2009 at 10:49:46
					</property>
				</relationship-definition>
				<relationship-definition
					name = 'decomposes'>
					<property
						name = 'alias'>
						<![CDATA[compose]]>
					</property>
					<property
						name = 'description'>
						<![CDATA[{\rtf1\ansi\ansicpg1252\uc0\deff0{\fonttbl
{\f0\froman\fcharset0\fprq2 Times New Roman;}}
{\colortbl;\red0\green0\blue0;\red255\green255\blue255;}
\deftab1134\pard\plain\f0\fs20 Relation de d\'e9composition descendante.}]]>
					</property>
					<property
						name = 'modificationStamp'>
						06/15/2009 at 14:20:38
					</property>
				</relationship-definition>
				<relationship-definition
					name = 'comprises'>
					<property
						name = 'alias'>
						<![CDATA[compose 2]]>
					</property>
					<property
						name = 'description'>
						<![CDATA[{\rtf1\ansi\ansicpg1252\uc0\deff0{\fonttbl
{\f0\froman\fcharset0\fprq2 Times New Roman;}}
{\colortbl;\red0\green0\blue0;\red255\green255\blue255;}
\deftab1134\pard\plain\f0\fs20 Un lien "compose" une interface.}]]>
					</property>
				</relationship-definition>
				<relationship-definition
					name = 'decomposed by'>
					<property
						name = 'alias'>
						<![CDATA[composé de]]>
					</property>
					<property
						name = 'description'>
						<![CDATA[{\rtf1\ansi\ansicpg1252\uc0\deff0{\fonttbl
{\f0\froman\fcharset0\fprq2 Times New Roman;}}
{\colortbl;\red0\green0\blue0;\red255\green255\blue255;}
\deftab1134\pard\plain\f0\fs20 Relation de d\'e9composition ascendante.}]]>
					</property>
					<property
						name = 'modificationStamp'>
						06/22/2009 at 10:50:16
					</property>
				</relationship-definition>
				<relationship-definition
					name = 'comprised of'>
					<property
						name = 'alias'>
						<![CDATA[composée de]]>
					</property>
					<property
						name = 'description'>
						<![CDATA[{\rtf1\ansi\ansicpg1252\uc0\deff0{\fonttbl
{\f0\froman\fcharset0\fprq2 Times New Roman;}}
{\colortbl;\red0\green0\blue0;\red255\green255\blue255;}
\deftab1134\pard\plain\f0\fs20 Une interface est "compos\'e9e de" liens.}]]>
					</property>
				</relationship-definition>
				<relationship-definition
					name = 'connects to'>
					<property
						name = 'alias'>
						<![CDATA[connecte]]>
					</property>
					<property
						name = 'description'>
						<![CDATA[{\rtf1\ansi\ansicpg1252\uc0\deff0{\fonttbl
{\f0\froman\fcharset0\fprq2 Times New Roman;}}
{\colortbl;\red0\green0\blue0;\red255\green255\blue255;}
\deftab1134\pard\plain\f0\fs20 Un lien "connecte" deux constituants.}]]>
					</property>
					<property
						name = 'modificationStamp'>
						06/15/2009 at 15:19:21
					</property>
				</relationship-definition>
				<relationship-definition
					name = 'connected to'>
					<property
						name = 'alias'>
						<![CDATA[connecté à]]>
					</property>
					<property
						name = 'description'>
						<![CDATA[{\rtf1\ansi\ansicpg1252\uc0\deff0{\fonttbl
{\f0\froman\fcharset0\fprq2 Times New Roman;}}
{\colortbl;\red0\green0\blue0;\red255\green255\blue255;}
\deftab1134\pard\plain\f0\fs20 Un constituant  est "connect\'e9 \'e0" un lien.}]]>
					</property>
					<property
						name = 'modificationStamp'>
						06/15/2009 at 15:18:44
					</property>
				</relationship-definition>
				<relationship-definition
					name = 'connects thru'>
					<property
						name = 'alias'>
						<![CDATA[connecte via]]>
					</property>
					<property
						name = 'description'>
						<![CDATA[{\rtf1\ansi\ansicpg1252\uc0\deff0{\fonttbl
{\f0\froman\fcharset0\fprq2 Times New Roman;}}
{\colortbl;\red0\green0\blue0;\red255\green255\blue255;}
\deftab1134\pard\plain\f0\fs20 Un lien "connecte" un constituant "via" son constituant p\'e8re.  (relation g\'e9n\'e9r\'e9e automatiquement par CORE).}]]>
					</property>
					<property
						name = 'modificationStamp'>
						06/15/2009 at 15:18:59
					</property>
				</relationship-definition>
				<relationship-definition
					name = 'connected thru'>
					<property
						name = 'alias'>
						<![CDATA[connecté via]]>
					</property>
					<property
						name = 'description'>
						<![CDATA[{\rtf1\ansi\ansicpg1252\uc0\deff0{\fonttbl
{\f0\froman\fcharset0\fprq2 Times New Roman;}}
{\colortbl;\red0\green0\blue0;\red255\green255\blue255;}
\deftab1134\pard\plain\f0\fs20 Un constituant est "connect\'e9" \'e0 un lien physique "via" son constituant fils (relation g\'e9n\'e9r\'e9e automatiquement par CORE).}]]>
					</property>
					<property
						name = 'modificationStamp'>
						06/15/2009 at 15:18:18
					</property>
				</relationship-definition>
				<relationship-definition
					name = 'consumes'>
					<property
						name = 'alias'>
						<![CDATA[consomme]]>
					</property>
					<property
						name = 'description'>
						<![CDATA[{\rtf1\ansi\ansicpg1252\uc0\deff0{\fonttbl
{\f0\froman\fcharset0\fprq2 Times New Roman;}}
{\colortbl;\red0\green0\blue0;\red255\green255\blue255;}
\deftab1134\pard\plain\f0\fs20 Une fonction ou une activit\'e9 "consomme" des ressources, qui diminuent d'autant. La ressource est consomm\'e9e au d\'e9but de l'activit\'e9.}]]>
					</property>
					<property
						name = 'modificationStamp'>
						06/15/2009 at 15:20:06
					</property>
				</relationship-definition>
				<relationship-definition
					name = 'consumed by'>
					<property
						name = 'alias'>
						<![CDATA[consommé par]]>
					</property>
					<property
						name = 'description'>
						<![CDATA[{\rtf1\ansi\ansicpg1252\uc0\deff0{\fonttbl
{\f0\froman\fcharset0\fprq2 Times New Roman;}}
{\colortbl;\red0\green0\blue0;\red255\green255\blue255;}